### ISSUE TITLE
[Refactor] Printing progress and outputs

### ISSUE THREAD

**Issue by SarcasticNastik** [bitcointranscripts/tstbtc#107]
# Using `Logging` Module

The current state of output (both debug and standard) relies on printing to stdout. This aims to shift the focus to use `logging` module ([SO link](https://stackoverflow.com/questions/6918493/in-python-why-use-logging-instead-of-print) for benefits of the same).

# Tasks

- [x] Replace all `print` statements with `logging` functionalities
    - #105 .
- [ ] Improve error messages and introduce _contextual information_ about the errors (TBD after basic refactor of the application).
    - [ ] Fix output format for general stuff after #105. For example, showing information as
    > 2023-06-06 03:25:18,977 - tstbtc - INFO -  This tool will convert Youtube videos to mp3 files and then transcribe them to text using Whisper.

    isn't what a package should ideally output.
    - [ ] At some places exceptions handling is used in logic only for logical purposes (specifying the type etc.). At such places, errors should not be raised (happening as of now).
    - [ ] Specify handlers for the library properly.

- [ ] Introduce exception traceback in the log messages.

**Comment by kouloumos** [comment]
Logging and exceptions handling is now part of the app.
